version: "3.3"
services:
  mysqldb:
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=tripPartner
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
  app:
    depends_on:
      - mysqldb
      - mongodb
    image: backend:0.1
    restart: on-failure
    ports:
      - "8079:8079"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tripPartner",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root1234",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.show-sql": "true",
        "spring.data.mongodb.uri": "mongodb://mongodb:27017/TripPartner"
      }'

